# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_logo = QtWidgets.QLabel(LoginWindow)
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout.addWidget(self.label_logo)
        self.label_title = QtWidgets.QLabel(LoginWindow)
        self.label_title.setText("")
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.email_input = QtWidgets.QLineEdit(LoginWindow)
        self.email_input.setObjectName("email_input")
        self.verticalLayout.addWidget(self.email_input)
        self.password_input = QtWidgets.QLineEdit(LoginWindow)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.role_combo = QtWidgets.QComboBox(LoginWindow)
        self.role_combo.setObjectName("role_combo")
        self.role_combo.addItem("")
        self.role_combo.addItem("")
        self.role_combo.addItem("")
        self.verticalLayout.addWidget(self.role_combo)
        self.login_button = QtWidgets.QPushButton(LoginWindow)
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Microfinance Manager - Login"))
        LoginWindow.setStyleSheet(_translate("LoginWindow", "background-color: #FFFFFF; font-family: Roboto;"))
        self.email_input.setPlaceholderText(_translate("LoginWindow", "Email"))
        self.password_input.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.role_combo.setItemText(0, _translate("LoginWindow", "Client"))
        self.role_combo.setItemText(1, _translate("LoginWindow", "Admin"))
        self.role_combo.setItemText(2, _translate("LoginWindow", "Loan Officer"))
        self.login_button.setText(_translate("LoginWindow", "Login"))
        self.login_button.setStyleSheet(_translate("LoginWindow", "background-color: #007BFF; color: white; border-radius: 5px; padding: 8px;"))
