# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        LoginWindow.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #007BFF, stop:1 #0056B3); font-family: Roboto;")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo_label = QtWidgets.QLabel(LoginWindow)
        self.logo_label.setText("<img src=\":/images/logo.png\" width=\"100\" height=\"100\"/>")
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout.addWidget(self.logo_label)
        self.title_label = QtWidgets.QLabel(LoginWindow)
        self.title_label.setStyleSheet("color: #FFFFFF; font-size: 24px; font-weight: bold;")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.email_input = QtWidgets.QLineEdit(LoginWindow)
        self.email_input.setMinimumSize(QtCore.QSize(300, 40))
        self.email_input.setStyleSheet("border: 1px solid #CED4DA; border-radius: 5px; padding: 5px; color: #000000; background: #FFFFFF;")
        self.email_input.setPlaceholderText("Email")
        self.email_input.setAlignment(QtCore.Qt.AlignCenter)
        self.email_input.setObjectName("email_input")
        self.verticalLayout.addWidget(self.email_input)
        self.password_input = QtWidgets.QLineEdit(LoginWindow)
        self.password_input.setMinimumSize(QtCore.QSize(300, 40))
        self.password_input.setStyleSheet("border: 1px solid #CED4DA; border-radius: 5px; padding: 5px; color: #000000; background: #FFFFFF;")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setPlaceholderText("Password")
        self.password_input.setAlignment(QtCore.Qt.AlignCenter)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        self.role_combo = QtWidgets.QComboBox(LoginWindow)
        self.role_combo.setMinimumSize(QtCore.QSize(300, 40))
        self.role_combo.setStyleSheet("border: 1px solid #CED4DA; border-radius: 5px; padding: 5px; color: #000000; background: #FFFFFF;")
        self.role_combo.addItem("")
        self.role_combo.addItem("")
        self.role_combo.setObjectName("role_combo")
        self.verticalLayout.addWidget(self.role_combo)
        self.login_button = QtWidgets.QPushButton(LoginWindow)
        self.login_button.setMinimumSize(QtCore.QSize(300, 40))
        self.login_button.setStyleSheet("background: #007BFF; color: #FFFFFF; border-radius: 5px; padding: 5px;")
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button)
        self.reset_password_button = QtWidgets.QPushButton(LoginWindow)
        self.reset_password_button.setMinimumSize(QtCore.QSize(300, 40))
        self.reset_password_button.setStyleSheet("background: transparent; color: #FFFFFF; border: 1px solid #FFFFFF; border-radius: 5px; padding: 5px;")
        self.reset_password_button.setObjectName("reset_password_button")
        self.verticalLayout.addWidget(self.reset_password_button)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Microfinance Manager - Login"))
        self.title_label.setText(_translate("LoginWindow", "Microfinance Manager"))
        self.role_combo.setItemText(0, _translate("LoginWindow", "Client"))
        self.role_combo.setItemText(1, _translate("LoginWindow", "Admin"))
        self.login_button.setText(_translate("LoginWindow", "Login"))
        self.reset_password_button.setText(_translate("LoginWindow", "Reset Password"))
